### ISSUE TITLE
添加新站点,复制选中站点地址,添加站点的窗口会消失

### ISSUE THREAD

**Issue by 663D74N** [Rhilip/IYUU-GUI#1]
版本: IYUU-GUI v1.0.3
位置:辅种站点设置>添加新站点

这个是软件本身问题还是我这里操作问题?

![11](https://user-images.githubusercontent.com/13313477/88494028-c0a9c280-cfe6-11ea-9b34-2e382987866c.gif)

**Comment by Rhilip** [comment]
不算bug，你点到外面的遮罩层了。
这个已经在 https://github.com/Rhilip/IYUU-GUI/commit/a600db23f7a38ed17ae3cfa84726ea4e8aca3fcf 中修了，但目前还没有发布。
具体的话，和PTPP的这个有点像 https://github.com/ronggang/PT-Plugin-Plus/issues/263
