### ISSUE TITLE
对macOS客户端可能为bug的情况反馈

### ISSUE THREAD

**Issue by tatsuz0u** [Rhilip/IYUU-GUI#10]
1. 状态栏图标严重横向拉伸变形
2. 启动时先要求输入token，然后要求输入站点ID和passkey，进入程序主界面后显示已添加站点为空

第一点显然是非预期效果
第二点推测是历史遗留代码，注意到进入主界面前要求输入站点信息时，站点列表记忆中只有五个，进入主界面后添加才看到有IYUU官方支持的那些

因为有GUI所以没怎么注意看文档，如果是误会，不好意思。

**Comment by Rhilip** [comment]
1. 本人没有macOS，所以这个状态栏图标具体拉伸情况不好判断。而且macOS下的构建策略是electron默认的，推测其中一些icon设置问题导致横向拉伸。
2. 就描述上应该是feature。原因在于，
  - 如果token在PHP版或者其他环境下已经绑定过了（IYUU服务器上有绑定数据），那么输入token就直接进入程序主界面了，不需要再输入站点ID和passkey等信息。而如果token是全新的，那么就可以使用这5个站点进行id和passkey的绑定。
  - 前面显示的五个站点是用来绑定的，因为只有绑定过才能使用后续功能，不然IYUU的API会报错。进入主界面添加站点才是支持站点。
  - 这块的交互逻辑确实和PHP版有所不同，因为PHP版只有一个配置文件，而GUI下可以将配置文件进行分散。所以交互逻辑就变成这样了。

**Comment by tatsuz0u** [comment]
> 1. 本人没有macOS，所以这个状态栏图标具体拉伸情况不好判断。而且macOS下的构建策略是electron默认的，推测其中一些icon设置问题导致横向拉伸。
> 
> 2. 就描述上应该是feature。原因在于，
> 
>   - 如果token在PHP版或者其他环境下已经绑定过了（IYUU服务器上有绑定数据），那么输入token就直接进入程序主界面了，不需要再输入站点ID和passkey等信息。而如果token是全新的，那么就可以使用这5个站点进行id和passkey的绑定。
> 
>   - 前面显示的五个站点是用来绑定的，因为只有绑定过才能使用后续功能，不然IYUU的API会报错。进入主界面添加站点才是支持站点。
> 
>   - 这块的交互逻辑确实和PHP版有所不同，因为PHP版只有一个配置文件，而GUI下可以将配置文件进行分散。所以交互逻辑就变成这样了。

明白了，感谢答复
