### ISSUE TITLE
macOS  种子下载链接构造失败、下载器hash缓存退出后丢失

### ISSUE THREAD

**Issue by tatsuz0u** [Rhilip/IYUU-GUI#11]
种子下载链接构造失败， 站点 hdchina 种子id： 28。原因： Error: 未提取到该ID的种子链接 (站点 hdchina ID 28)

**Comment by tatsuz0u** [comment]
暂时没有其它需要通过cookie辅种的站点，所以只有瓷器报错。

**Comment by Rhilip** [comment]
😂写错该站点的链接构造方法了 v1.0.7应该已经修了
