### ISSUE TITLE
PThome改用downhash了

### ISSUE THREAD

**Issue by lzq1206** [Rhilip/IYUU-GUI#18]
PThome改用downhash了
https://pthome.net/download.php?id={}&downhash={}

**Comment by Rhilip** [comment]
不好意思，由于目前没太多精力放在此项目上，且由于官方IYUU-PLUS项目，以及本人想在PTPP中集成IYUU功能的想法，
所以该项目有archive的想法，

-------------

因此目前只能先以 强制Cookies 的形式来解决以上站点的下载问题。
