### ISSUE TITLE
能否支持群晖，实现定时辅种

### ISSUE THREAD

**Issue by mjyhj** [Rhilip/IYUU-GUI#2]
GUI给力，不过WEB GUI好像更方便。
请问能否支持群晖运行，这样就可以一直运行，实现定时辅种。

另外目前好像没有 转移做种的功能

**Comment by Rhilip** [comment]
请选择PHP版
本人对于此项目的定位是：如果没使用过IYUU的人，想要尝试或者想要了解，又苦于没有相关基础，直接上手官方PHP版较为困难，使用本项目可以对整个IYUU的实现及功能进行了解，能为后续进阶使用提供机会。

-----------

1. 本人对WEB GUI不感兴趣，如果你有能力或者其他人有能力，可以基于目前的代码修改形成。毕竟都是拿前端框架写的，改起来也简单。
2. 无群晖，不清楚。
3. 转移做种有在计划中，目前请用PHP版替代。
