### ISSUE TITLE
空辅种报错

### ISSUE THREAD

**Issue by Xxx00xxX33** [Rhilip/IYUU-GUI#9]
输入cookie执行辅种任务报错， 信息如下：
种子下载链接构造失败， 站点 hdsky 种子id： 4。原因： TypeError: Cannot read property 'startsWith' of undefined

**Comment by Rhilip** [comment]
用的是qbt作为客户端？
似乎是因为没有这个种子了吧？然后没有抓到下载链接。
我稍微改下

**Comment by Xxx00xxX33** [comment]
是的大佬 我用的是qb

**Comment by Rhilip** [comment]
v1.0.7 应该已经修了，如果还有问题再reopen吧
